### ISSUE TITLE
[Request] Windows release

### ISSUE THREAD

**Issue by gd4c** [svenslaggare/sqlgrep#1]
SQL + GREP together make this tool very interesting and I'd like to ask you for a Windows release.

Thanks

**Comment by svenslaggare** [comment]
Don't got a working Windows machine sadly.

**Comment by gd4c** [comment]
VM?

**Comment by svenslaggare** [comment]
GitHub Actions seems to have Windows workers, so I managed to get a build using that (see release [v0.2.1](https://github.com/svenslaggare/sqlgrep/releases/tag/v0.2.1)).
Can't test it though, but it passed all unit tests.

**Comment by gd4c** [comment]
Working well. Thank you!

Although, what's with the need to double escape some regex characters (for example, `\\d`, `\\t`)?
